#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHANNELS=(operator_logic terminalecho blackledger nullsignal)

for channel in "${CHANNELS[@]}"; do
  voice_dir="${ROOT_DIR}/assets/voices/${channel}"
  mkdir -p "${voice_dir}"

  if [[ ! -f "${voice_dir}/README.md" ]]; then
    cat > "${voice_dir}/README.md" <<EOF
# ${channel} Voice Reference

Place the licensed or owned Chatterbox reference file here as:

- reference.wav

No fake audio is generated by this setup script.
EOF
  fi

  if [[ ! -f "${voice_dir}/reference.wav" ]]; then
    echo "[setup] missing ${voice_dir}/reference.wav"
  else
    echo "[setup] found ${voice_dir}/reference.wav"
  fi
done
